export const STT_CORRECTIONS: [RegExp, string][] = [
  // Team members
  [/\bBiomech\b/gi, "Biobak"],
  [/\bBiomek\b/gi, "Biobak"],
  [/\bBiomag\b/gi, "Biobak"],
  [/\bBiobike\b/gi, "Biobak"],
  [/\bBiomex\b/gi, "Biobak's"],
  [/\bBadoop\b/gi, "Badub"],
  [/\bBadoob\b/gi, "Badub"],
  [/\bBadoo\b/gi, "Badub"],
  [/\bBadou\b/gi, "Badub"],
  [/\bBadoub\b/gi, "Badub"],
  [/\bBarduke\b/gi, "Badub"],
  [/\bBad00p\b/gi, "Badub"],
  [/\bXena\b/gi, "Zeina"],
  [/\bZena\b/gi, "Zeina"],
  [/\bZeyna\b/gi, "Zeina"],
  [/\bLeela\b/gi, "Lilaa"],
  [/\bLeila\b/gi, "Lilaa"],
  [/\bLeyla\b/gi, "Lilaa"],
  [/\bLayla\b/gi, "Lilaa"],
  [/\bLaila\b/gi, "Lilaa"],
  [/\bLila\b/gi, "Lilaa"],
  [/\bSauron\b/gi, "Sauraen"],
  [/\bSaurin\b/gi, "Sauraen"],
  [/\bSauren\b/gi, "Sauraen"],
  [/\bAza\b/gi, "Aeza"],
  // Technical terms
  [/\bf3dx\b/gi, "F3DEX"],
  [/\bF3DX2\b/g, "F3DEX2"],
  [/\bF3DX3\b/g, "F3DEX3"],
  [/\bf3d\s*x2\b/gi, "F3DEX2"],
  [/\bf3d\s*x3\b/gi, "F3DEX3"],
  [/\bLib\s*Dragon\b/gi, "libdragon"],
  [/\bRom[Ee]x\b/g, "ROM hack"],
  [/\bromex\b/g, "ROM hack"],
];
